// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVUOXH8eXxm9AI2yEqL1fjCRUIoZEqM4',
    appId: '1:832598111423:web:155bb848d8a72cafbbc20a',
    messagingSenderId: '832598111423',
    projectId: 'flutter-chat-app01-6f1cc',
    authDomain: 'flutter-chat-app01-6f1cc.firebaseapp.com',
    storageBucket: 'flutter-chat-app01-6f1cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CVWzH2pDg3G2we1kMwS9VuCg50L0pao',
    appId: '1:832598111423:android:d03ebf2aa8bb0110bbc20a',
    messagingSenderId: '832598111423',
    projectId: 'flutter-chat-app01-6f1cc',
    storageBucket: 'flutter-chat-app01-6f1cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkt20VgIV2KYl4YhN_1ijqkhISo5QKKc',
    appId: '1:832598111423:ios:e6e2861b27d638d7bbc20a',
    messagingSenderId: '832598111423',
    projectId: 'flutter-chat-app01-6f1cc',
    storageBucket: 'flutter-chat-app01-6f1cc.appspot.com',
    iosClientId: '832598111423-fgu1vm918669jh0ird5659maulb75t8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkt20VgIV2KYl4YhN_1ijqkhISo5QKKc',
    appId: '1:832598111423:ios:e67b8e4c45454f37bbc20a',
    messagingSenderId: '832598111423',
    projectId: 'flutter-chat-app01-6f1cc',
    storageBucket: 'flutter-chat-app01-6f1cc.appspot.com',
    iosClientId: '832598111423-a1eivjmghc5fi8c33lht364sq99dllp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp01.RunnerTests',
  );
}
